### PR TITLE
Cad tutorial

### PR DESCRIPTION
**Pull request by JoostGevaert**
Frist of all, **thank you** for submitting a pull request. We appreciate that you follow the spirit of open-source and that you are willing to contribute to pyGIMLi. Please make sure that this PR is targeted to the `dev` branch. If not, please [change this now](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request). Additional notes on development can be found on [pygimli.org/dev](https://www.pygimli.org/dev).

### CODE REVIEW

**Comment by JoostGevaert** [comment]
Oh sorry, I wasn't aware that I committed the `plot_bert-logo.html`. I thought that was in the .gitignore

**Comment by JoostGevaert** [comment]
Let's add the conda install gmsh to the tutorial quickly

**Comment by halbmy** [comment]
Dear Joost, great job! We need more guys like you... Thomas

**Comment by halbmy** [comment]
I'm gonna try it on a CAD model of an embankment dike I have been modelling. But this might take a bit...

**Comment by carsten-forty2** [comment]
Hello Joost, 
great example .. thanks a lot for your contribution.

Carsten

**Comment by JoostGevaert** [comment]
Amazing, now it's merged with the dev branch. When will the example go online? :)

**Comment by florian-wagner** [comment]
I cherry picked it to the release branch. Should be up on the website tomorrow. Thanks, joost!

**Comment by JoostGevaert** [comment]
Amazing!

**Comment by JoostGevaert** [comment]
> I cherry picked it to the release branch. Should be up on the website tomorrow. Thanks, joost!

Is it possible that the example is not online yet?

**Comment by halbmy** [comment]
It is available only in the development version (dev.pygimli.org) under Examples or here
http://www2.geo.uni-bonn.de/~wagner/pygimli/html/_examples_auto/1_meshing/plot_cad_tutorial.html#sphx-glr-examples-auto-1-meshing-plot-cad-tutorial-py
but not yet on the main pygimli.org page.

**Comment by JoostGevaert** [comment]
Oke, I understand. Thanks
How come that the tumbnail of the example is not showing up?
I thought `# sphinx_gallery_thumbnail_path = '_static/cad_tutorial/gmsh_fig.png'` would make the `gmsh_fig.png` the tumbnail of the example.

**Comment by florian-wagner** [comment]
Hi @JoostGevaert,

sorry, my bad. I just checked dev.pygimli.org. It is now live on pygimli.org: https://www.pygimli.org/_examples_auto/index.html

The thumbnail line was perfectly fine, but it seems that it has to appear below the first string block. I fixed this here: https://github.com/gimli-org/gimli/commit/1aecb78acc87b9346f0aa407c8df124ac966e147

(This produces one empty code cell at the top for some reason, but this is likely a sphinx-gallery issue. At least the thumbnail is working.)

Thanks again for your contribution and sorry for the delay on my side,
Florian

**Comment by JoostGevaert** [comment]
Amazing!
Thanks

**Pull request merged**
