### PR TITLE
Added contributing to documentation guidelines 

### PR DESCRIPTION
**Pull request by andieie**
Added contributing to doc guidelines following the procedure we did on my computer. Let me know if this helps. A more general contributing guideline is needed ( for those without writing privileges). Let me know if what I have done (open fork and do a PR) is the way to go. 

Thanks!

### CODE REVIEW

**Comment by carsten-forty2** [comment]
Thanks for the PR. It is possible to somehow merge or update doc/contrib.rst .. 
Are there redundancies now? Maybe we can use dev.rst as a coarse coding and documentation guidline and contrib.rst as the description on how to contribute?

**Comment by andieie** [comment]
I will take a look at doc/contrib.rst and merge any redundancies. I agree contrib.rst can have the description on how to contribute using git and dev.rst can have the guidelines, formatting styles and everything else. Dev.rst should then link to contrib.rst.

**Comment by florian-wagner** [comment]
And the other way round. Right now contrib is linked quite prominently (Documentation -> Contributing), whereas the link to dev is somewhat hidden within contrib.rst (link to the section testing).: https://www.pygimli.org/contrib.html

**Comment by andieie** [comment]
Updated dev.rst and contrib.rst and I've also added an environment.yml.

**Comment by carsten-forty2** [comment]
Cool .. looks good to me .. thank you a lot!!

**Comment by florian-wagner** [comment]
Thank you @andieie ! I will make some minor changes (typo in environment name in .yml file and pygimli should not be part of the dependencies, as developers should use the git source), but other than that, it reads really well. The jenkins failure afterwards was unrelated by the way, I have to install gmsh. http://jenkins.pygimli.org/job/pyGIMLi_dev/646/console

**Pull request merged**
