### PR TITLE
SIP examples

### PR DESCRIPTION
**Pull request by m-weigand**
This branch includes two examples for generating SIP spectra and fitting the Cole-Cole model or a Debye decomposition approach to the data.

Descriptions could probably be improved, but I think this will do for starters.

### CODE REVIEW

**Comment by florian-wagner** [comment]
@m-weigand Thanks a lot for this valuable contribution!
@halbmy Can you look through this and click "Squash and merge" if you're happy?

**Comment by florian-wagner** [comment]
I fast forwarded this due to the IP workshop in Aachen, however, your comments are still welcome of course.

**Comment by halbmy** [comment]
Sorry, I have been on vacations. You already squashed the six commits into a single one and merged it into the dev branch?

The two examples look great, thanks to @m-weigand for the contribution!
I am not sure whether **Generating SIP signatures** is really needed as example since it contains many handwork (for which there are ready functions) and is repeated by **Fitting SIP signatures**. Also not sure whether for the latter large parts of the code should be repeated. Actually there are three examples in one file, different from other examples where we add part-by-part.

We could add some information on what the second (high-frequency) EM term is meant for and why the Kramers-Kronig relations show a shift due to the limited frequency range. Interesting to see that `sip.removeEpsilonEffect()` cannot remove the high-frequency term as it is still in the frequency range. Shifting the tau below 1e-7 the function works well and is in my opinion superior as it strictly removes the high-frequency stuff that cannot be attributed to mechanisms non-ambiguously anyway.

**Comment by m-weigand** [comment]
1) The idea of the **Generating SIP signatures** example was that people look for specific things they want to do, i.e., generate a Cole-Cole type signature. This is different from fitting an SIP spectrum. So yes, it contains code that is later repeated, but in another context. Should I delete it? If you point me to the high-level functions that simplify this generation, I will update the examples.

2) Yes, in the **Fitting SIP signatures** example I created three separate examples that highlight different aspects of fitting SIP signatures. Code was repeated in order to get three complete examples that can be copy&pasted (that's how I usually use example sections).
I see two options here: Split into three separate examples, or delete some parts. Merging into one example would show duplicating functionality within one example (Cole-Cole fit AND Debye decomposition). I think this could confuse new users that are still trying to understand things and only want to accomplish one thing.

3) I haven't looked at the Kramers&Kronig-functions in detail, but my understanding is that they work only for infinite frequency bands (or if peaks are completely captured by the data). Otherwise it would be better to just fit a Cole-Cole model or a Debye decomposition to check the validity of the data (these functions also imply Kramers&Kronig relations, so any deviation from a successful fit is also a deviation from the relationship, right?).

4) Regarding the EM-Removal, I'm not sure what you are suggesting here. Should I change the tau of the forward model?

**Comment by halbmy** [comment]
1. I just meant that generating the SIP signature is also the first step in the fitting example and could be done there in more detail so that just one longer example remains that does it all. What do the others think?

2. I totally got the point of the three encapsulated examples. It is more a design question to all developers (including you) if we want to stick to a typical way or if several examples in one file are ok as well.

3. Agree, K&K works perfectly for wide frequency bands, but if all the relaxations are within the measured band it is working as well. For me it is a good check for consistency of real measured data. So the examples are indeed illustrative.

4. I was just curious whether the two methods (fitting an EM term and fitting an omega i epsilon term) yield the same, and they do it if tau is very small (in this case I would prefer the second due to its simplicigy) but not if it is close to the measured frequency band (in this case I would prefer the first one). The example could show two different high-frequency taus.

**Pull request merged**
