### PR TITLE
Refactor / cleanup

### PR DESCRIPTION
**Pull request by robinthibaut**
I made some small adjustments to tidy up the pygimli code:

Code Formatting:
I ran [black](https://pypi.org/project/black/) to format the code consistently according to[ PEP8](https://peps.python.org/pep-0008/) standards.

Optimized Imports:
I simply optimized the imports, removing any unused ones and organizing them better to keep the code clean and readable.

Why: 
The goal was to make the codebase easier to work with by ensuring consistent formatting and keeping the imports organized. This helps maintain a clean, maintainable codebase for future development.

### CODE REVIEW

**Comment by halbmy** [comment]
Dear Robin, thank you for your effort. Code cleanup is very important, although we usually just do it step by step when working on some files anyway. And we might have some "alternative" styles for historic reasons.
However, your branch is conflicting with the development branch as it has been forked from the master branch. Typically, dev is merged master if all tests run through, but our Jenkins server that does the job is currently not running. I would suggest to give it another try when the build chain is again in order and to check whether we want to follow all PEPs strictly. Thomas

**Comment by halbmy** [comment]
But it is a good chance to discuss the code style:
* black changed all simple quotation marks `'`into double `"`, I know we are inconsequent but skipping this one will make the review process much simpler
* we deliberately shifted some imports to inside functions to speed up the import
* some images (logos etc.) were replaced for some unknown reason
* mass imports (e.g. from core) into single lines for every symbol become extremely lengthy and destroys overview
* having every keyword argument on one line can make sense sometimes but can also destroy readability (I personally prefer code using the 80 character of the editor over ones with thousands of lines), it is not a strict PEP rule

Actually, I am inclined to decline the PR but I would like to hear other opinions.
*

**Comment by carsten-forty2** [comment]
We will not accept mass code changes as PR .. we would need to check every single line of code to look for side effects. 

I took a look for the 'black' tool if we can apply it ourself instead but I find the possibilities for configuration to limited.
e.g., I strongly disklike there way of indentation function arguments. For me, it changes the visiblity and feel of the code to much, btw. the kind it is .. is already valid pep8 (https://peps.python.org/pep-0008/#indentation)

The single quotation is easier to type on german keyboards so we want to keep it this way .. and so we also follow the recommandation of pep8.

I agree there are some needed changes that would be good to tidying up the code and I would apply it for you to avoid mass change PR's .. If there is a tool that can be configured to fit our needs.

**Comment by robinthibaut** [comment]
Dear Thomas and Carsten,

Thank you for the feedback on the PR—I understand your concerns about avoiding large-scale changes.

Looking back, I should have started a discussion before making these adjustments. My main motivation was to clean up unnecessary import statements, unused variables, and arguments in functions that I came across.

I think it would be useful to implement unit tests for each function. Unit tests can help ensure that changes don't introduce bugs by verifying that each part of the code behaves as expected. For example, a test for a function like calculate_resistivity would check whether the function produces the correct output for a given set of inputs:

```python
def test_calculate_resistivity():
    input_data = [input values]
    expected_output = [expected result]
    assert calculate_resistivity(input_data) == expected_output
```

These unit tests can be integrated with GitHub using Continuous Integration (CI) tools like GitHub Actions. This setup would allow tests to run automatically whenever a PR is opened or updated, flagging any issues early on. The CI pipeline would generate reports showing which tests passed or failed, ensuring that changes don’t introduce bugs and maintaining code quality.

I noticed there’s a "testing" folder in the repository, but it seems the tests may be outdated. It could be worthwhile to update these tests to better reflect the current state of the codebase.

I’m happy to help with this if the team agrees it’s a good approach.

Robin

**Comment by carsten-forty2** [comment]
We have currently three levels of tests that are part of our CI pipline using a jenkins infrastructure. They will be called after every commit.

1. ApiDoc tests:
e.g., https://github.com/gimli-org/gimli/blob/7f86c39c6de3a2d9a15cc863a1d15614880a89fe/pygimli/utils/utils.py#L203

2. The content of the testing folder. 
Some of them might be outdated but they are all valid tests that needs to pass before the `dev` branch is merged automatic into the `master` branch

3. The examples and tutorials are build by jenkins to check if they all run as supposed to be.

You can force the testing manual with:

`python -c 'import pygimli as pg; pg.test()' ` currently only with a bug that annoys with open figures (we need to fix this soonish)

I don't know if its possible to integrate all these tests into a github-ci-pipline because the pipline would need to force core rebuilds, if some of the core c++ sources had been changed.

I agree that more unit tests would be great and I personaly prefer 'test-driven-development' where I first write the unit test and implement the functionality afterwards. But its always a question of time. Also test coverage overview would be great .. but you know .. time ...

**Comment by halbmy** [comment]
Dear Robin, even though the PR was declined, you raised our awareness on code cleanup and I am pretty sure we will improve the code style more in the future. And increase the coverage of the tests and examples. So thank you for your valuable feedback!

**Pull request closed without merging**
