### PR TITLE
Fix documentation for linux install

### PR DESCRIPTION
**Pull request by m-weigand**
This is a request-for-comment pull request, not really a pull request ;-)

The Debian packages required to build pygimli were incomplete and outdated for the current stable Debian (stretch). As you already have an Ubuntu section, I propose to make the Linux Debian section more specific and target Debian stretch (this will reduce misconception regarding the linux distribution where the instructions actually work).

I tested building pygimli using a Docker container based on the official Debians stretch Docker image (debian:stretch). As this could be interesting I also added the Dockerfile to the repository and added a small section in the linux installation instructions. Depending on your preferences I can either delete the Dockerfile, or move it to a location where it belongs. Also, I was not able to add a link to the Dockerfile in the linux installation instructions. Advise would be welcome.

### CODE REVIEW

**Comment by carsten-forty2** [comment]
Great!! .. thank you very much!

**Comment by carsten-forty2** [comment]
Since the docker style install is not our default mechanism and only valid for debian so far .. can you please move this file from root to scripts/ and change the name a bit so it reflects the debian base?

**Comment by m-weigand** [comment]
done. I also added a note to the installation instructions that this is only for advanced users.

**Comment by carsten-forty2** [comment]
Thank you very much .. I like it .. merge.

**Pull request merged**
